name: CI_TECSUnit

on: [push]

jobs:
  TECSUnit:
    runs-on: ubuntu-latest
    steps:
      - name: Get Actions
        uses: actions/checkout@v2
      
      - name: TECSUnit
        run: |
          cd hr-tecs/tecsgen
          source set_env.sh
          cd TECSUnit
          make clean
          make tecs
          make
          ./TECSUnit.exe
