name: CI_TECSUnit

on: [push]

jobs:
  TECSUnit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set _env
        run: |
          echo Hello
          cd hr-tecs/tecsgen
          source set_env.sh

      - name: TECSUnit
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          make clean
          make tecs
          make
          ./TECSUni.exe
