name: learn-github-actions

on: [push]

jobs:
  CI_test_TECSUnt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TECSUnit
        run: | 
          cd hr-tecs/tecsgen
          ls
          source set_env.sh
          cd TECSUnit
          make clean
          make tecs
          make
          ./TECSUnit.exe
