name: learn-github-actions

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd hr-tecs/tecsgen
      - run: source set_env.sh
      - run: cd TECSUnit
      - run: make clean
      - run: make tecs
      - run: make
