name: CI_TECSUnit

on:
  push:
    branches:
      - workspace

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: set env
        run: |
          cd hr-tecs/tecsgen
          echo "TECSPATH=$PWD/tecsgen/tecs" >> $GITHUB_ENV
          
      - name: make
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          make
      
      - name: execution
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          ./TECSUnit.exe
      
      - name: test result
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          cat test_result.txt >> $GITHUB_STEP_SUMMARY
          
      - name: gcov
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          gcov gen/*.gcda >> $GITHUB_STEP_SUMMARY
          cat *.gcov
          
      - name: lcov
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          lcov -d . -c -o coverage_test.info
          genhtml coverage_test.info -o ./info