name: CI_TECSUnit

on: [push]

jobs:
  TECSUnit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TECSUnit
        run: |
          cd hr-tecs/tecsgen
          source set_test.sh
          
